### ISSUE TITLE
Installation on ubuntu 14.04 not working

### ISSUE THREAD

**Issue by devroyaldev** [keystonejs/generator-keystone#160]
Hello,
I'm trying to use the generator under ubuntu but i get always the following error:

```
_SOMEUSER@MYHOST~$ sudo npm install -g generator-keystone
[sudo] password for SOMEUSER: 
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
 
> buffertools@2.1.3 install /usr/local/lib/node_modules/generator-keystone/node_modules/keystone-utils/node_modules/slug/node_modules/unicode/node_modules/bufferstream/node_modules/buffertools
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/SOMEUSER/.node-gyp/4.4.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/generator-keystone/node_modules/keystone-utils/node_modules/slug/node_modules/unicode/node_modules/bufferstream/node_modules/buffertools/.node-gyp"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/opt/node/lib/node_modules/npm/node_modules/which/which.js:63:19)
gyp ERR! stack     at E (/opt/node/lib/node_modules/npm/node_modules/which/which.js:72:29)
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/which.js:81:16
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.13.0-79-generic
gyp ERR! command "/opt/node/bin/node" "/opt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/generator-keystone/node_modules/keystone-utils/node_modules/slug/node_modules/unicode/node_modules/bufferstream/node_modules/buffertools
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm WARN optional dep failed, continuing buffertools@2.1.3
/
_
``

i have the issues using nodejs 4.4.0 and 5.8.0. The error is always the same.

I cannot run the yo command . I get always command not found.`

**Comment by morenoh149** [comment]
do you have make installed?

**Comment by devroyaldev** [comment]
That was the right hint. Don't know why i did not see it. 
After installing make and g++ . The installation of the keystone generator works.
Thanks.
