### ISSUE TITLE
Nunjucks can't find correct template path with consolidate 0.14.1

### ISSUE THREAD

**Issue by xres** [keystonejs/generator-keystone#181]
consolidate introduced a change in [v0.14.1](https://github.com/tj/consolidate.js/pull/152) that passes the views path to Nunjucks.

Here's my workaround:

**keystone.js**
```
keystone.init({
  'views': ['templates', 'templates/views'],
```

**views/index.html**
```
{% extends "layouts/default.html" %}
```

If I'm on the right path, I can create a PR.

**Comment by mxstbr** [comment]
I'm not entirely sure what the problem here is, how do I replicate that?

**Comment by xres** [comment]
Update consolidate to the current version, 0.14.1, this is the error I see:

```
Error thrown for request: /
Error: template not found: templates/layouts/default.html
    at null.<anonymous> (/Users/dev/test/my-site/node_modules/nunjucks/src/environment.js:175:31)
    at next (/Users/dev/test/my-site/node_modules/nunjucks/src/lib.js:203:13)
    at handle (/Users/dev/test/my-site/node_modules/nunjucks/src/environment.js:157:25)
    at /Users/dev/test/my-site/node_modules/nunjucks/src/environment.js:171:21
    at next (/Users/dev/test/my-site/node_modules/nunjucks/src/lib.js:200:13)
    at Object.exports.asyncIter (/Users/dev/test/my-site/node_modules/nunjucks/src/lib.js:207:5)
    at Obj.extend.getTemplate (/Users/dev/test/my-site/node_modules/nunjucks/src/environment.js:150:17)
    at root [as rootRenderFunc] (eval at <anonymous> (/Users/dev/test/my-site/node_modules/nunjucks/src/environment.js:450:24), <anonymous>:7:5)
    at null.<anonymous> (/Users/dev/test/my-site/node_modules/nunjucks/src/environment.js:387:18)
    at Object.exports.withPrettyErrors (/Users/dev/test/my-site/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/Users/dev/test/my-site/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Users/dev/test/my-site/node_modules/nunjucks/src/environment.js:261:21)
    at Object.module.exports.renderString (/Users/dev/test/my-site/node_modules/nunjucks/index.js:66:14)
    at /Users/dev/test/my-site/node_modules/consolidate/lib/consolidate.js:1101:16
    at /Users/dev/test/my-site/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/dev/test/my-site/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/dev/test/my-site/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/Users/dev/test/my-site/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/Users/dev/test/my-site/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.nunjucks.render (/Users/dev/test/my-site/node_modules/consolidate/lib/consolidate.js:1091:10)
    at /Users/dev/test/my-site/node_modules/consolidate/lib/consolidate.js:164:27
    at /Users/dev/test/my-site/node_modules/consolidate/lib/consolidate.js:98:5
    at fs.js:334:14
    at /Users/dev/test/my-site/node_modules/nunjucks/node_modules/graceful-fs/graceful-fs.js:104:5
    at /Users/dev/test/my-site/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by mxstbr** [comment]
Ah right, yeah that's a problem! :grin:

Would you mind submitting a PR with your fix? It looks pretty solid!
