### ISSUE TITLE
Error on npm test

### ISSUE THREAD

**Issue by joggienl** [keystonejs/generator-keystone#202]
Hello,

I tried to run 'npm test' on the latest version. Something goes wrong while executing 'eslint .'. Any idea's / suggestions? It looks like it can't find the additional modules in node_modules..

I've tried to run this on different node/npm versions.. all the same results..

Output npm test (npm-debug.log is not created...):
```
$ npm test

> generator-keystone@0.3.16 test /home/jogchum/Workspaces/Github/generator-keystone
> npm run lint && mocha


> generator-keystone@0.3.16 lint /home/jogchum/Workspaces/Github/generator-keystone
> eslint .


/home/jogchum/Workspaces/Github/generator-keystone/app/index.js
   27:33  error  Missing space before function parentheses             space-before-function-paren
  125:17  error  Expected indentation of 4 tab characters but found 0  indent

✖ 2 problems (2 errors, 0 warnings)


npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/jogchum/.nvm/versions/node/v6.2.0/bin/node" "/home/jogchum/.nvm/versions/node/v6.2.0/bin/npm" "run" "lint"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! generator-keystone@0.3.16 lint: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the generator-keystone@0.3.16 lint script 'eslint .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the generator-keystone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs generator-keystone
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls generator-keystone
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jogchum/Workspaces/Github/generator-keystone/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

Output npm run lint:
```
$ npm run lint

> generator-keystone@0.3.16 lint /home/jogchum/Workspaces/Github/generator-keystone
> eslint .


/home/jogchum/Workspaces/Github/generator-keystone/app/index.js
   27:33  error  Missing space before function parentheses             space-before-function-paren
  125:17  error  Expected indentation of 4 tab characters but found 0  indent

✖ 2 problems (2 errors, 0 warnings)


npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/jogchum/.nvm/versions/node/v6.2.0/bin/node" "/home/jogchum/.nvm/versions/node/v6.2.0/bin/npm" "run" "lint"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! generator-keystone@0.3.16 lint: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the generator-keystone@0.3.16 lint script 'eslint .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the generator-keystone package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs generator-keystone
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls generator-keystone
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jogchum/Workspaces/Github/generator-keystone/npm-debug.log
```
npm-debug.log:
```
$ cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/home/jogchum/.nvm/versions/node/v6.2.0/bin/node',
1 verbose cli   '/home/jogchum/.nvm/versions/node/v6.2.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@3.9.3
3 info using node@v6.2.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle generator-keystone@0.3.16~prelint: generator-keystone@0.3.16
6 silly lifecycle generator-keystone@0.3.16~prelint: no script for prelint, continuing
7 info lifecycle generator-keystone@0.3.16~lint: generator-keystone@0.3.16
8 verbose lifecycle generator-keystone@0.3.16~lint: unsafe-perm in lifecycle true
9 verbose lifecycle generator-keystone@0.3.16~lint: PATH: /home/jogchum/.nvm/versions/node/v6.2.0/lib/node_modules/npm/bin/node-gyp-bin:/home/jogchum/Workspaces/Github/generator-keystone/node_modules/.bin:/home/jogchum/.nvm/versions/node/v6.2.0/bin:/home/jogchum/.nvm/versions/node/v6.2.0/bin:/home/jogchum/.npm-global/bin:/opt/maven-current/bin:/opt/intellij-current/bin:/opt/webstorm-current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle generator-keystone@0.3.16~lint: CWD: /home/jogchum/Workspaces/Github/generator-keystone
11 silly lifecycle generator-keystone@0.3.16~lint: Args: [ '-c', 'eslint .' ]
12 silly lifecycle generator-keystone@0.3.16~lint: Returned: code: 1  signal: null
13 info lifecycle generator-keystone@0.3.16~lint: Failed to exec lint script
14 verbose stack Error: generator-keystone@0.3.16 lint: `eslint .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/jogchum/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/jogchum/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid generator-keystone@0.3.16
16 verbose cwd /home/jogchum/Workspaces/Github/generator-keystone
17 error Linux 4.4.0-22-generic
18 error argv "/home/jogchum/.nvm/versions/node/v6.2.0/bin/node" "/home/jogchum/.nvm/versions/node/v6.2.0/bin/npm" "run" "lint"
19 error node v6.2.0
20 error npm  v3.9.3
21 error code ELIFECYCLE
22 error generator-keystone@0.3.16 lint: `eslint .`
22 error Exit status 1
23 error Failed at the generator-keystone@0.3.16 lint script 'eslint .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the generator-keystone package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     eslint .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs generator-keystone
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls generator-keystone
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mxstbr** [comment]
Well, the error message you're getting from linting says it all :grin:

```
/home/jogchum/Workspaces/Github/generator-keystone/app/index.js
   27:33  error  Missing space before function parentheses             space-before-function-paren
  125:17  error  Expected indentation of 4 tab characters but found 0  indent
```

Add a space before the function paratheses in `app/index.js:27:33`, and fix the indentation at `app/index.js:125:15`!

Did you edit anything before running this?

**Comment by joggienl** [comment]
No I did not edit anything before. This is as it runs when you clone the repo. The linting errors are clear, but I don't get why NPM should exit the way it does. Normally I would expect it to exit like:

```
npm ERR! Test failed.  See above for more details.
```

Fixing the lint errors do make a difference, so indeed they have something to do with it. Seems like NPM should interpret it different I guess.

**Comment by mxstbr** [comment]
No, that's the right behaviour. If linting fails, npm should fail. It's part of the test suite!

**Comment by joggienl** [comment]
Thanks for your answer!

In terms of the "right" behaviour I think that depends on when/how you run the test. If it should break after the first error found, it should exit after the first found lint error (which it doesn't). When just running a test like specified now, I would not mind to have both tests run (nevertheless either of them totally blows up). With both tests I mean the eslint and the mocha tests.

Technically from NPM perspective, NPM received an exit 1; which should stop NPM from processing any further. Exactly as described in the NPM docs (https://docs.npmjs.com/misc/scripts#exiting). Maybe I should have read that part more carefully before ;-). I was confused by the big error exit..

I do have a suggestion for change. The scripts part in package.json now has this:

```
"scripts": {
  "lint": "eslint .",
  "lint-fix": "eslint . --fix",
  "test": "npm run lint && mocha"
}
```

When linting fails, it gives the big messasge as said before. I've also tried to change it as shown below. The difference is to use "eslint ." in stead of "npm run lint":

```
"scripts": {
  "lint": "eslint .",
  "lint-fix": "eslint . --fix",
  "test": "eslint . && mocha"
}
```
When linting fails it now does this:

```
$ npm test

> generator-keystone@0.3.16 test /home/jogchum/Workspaces/Github/generator-keystone
> eslint . && mocha


/home/jogchum/Workspaces/Github/generator-keystone/app/index.js
  302:10  error  Infix operators must be spaced  space-infix-ops

✖ 1 problem (1 error, 0 warnings)

npm ERR! Test failed.  See above for more details.
```

So my suggestion would be to specify the test as "eslint . && mocha" in package.json. I don't see any advantage in running it with "npm lint" when eslint is directly available for the script execution. It could be however that there have been specific reasons to do it like this. Are there?
