### ISSUE TITLE
Error when Creating project w/ user model set to AdminUser

### ISSUE THREAD

**Issue by rturk** [keystonejs/generator-keystone#203]
If I attempt to create a new project with

? What would you like to call the User model? **AdminUser**

Will produce the following error:
keystone.js:54
    admin-users: 'admin-users',
         ^
SyntaxError: Unexpected token -
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

**Comment by Noviny** [comment]
This issue occurs as in the keystone.js file, a hyphenated object name is created without using quotation. #233 resolves this.
