### ISSUE TITLE
Cant start Keystone in windows

### ISSUE THREAD

**Issue by AkshayMuralidhara** [keystonejs/generator-keystone#223]
Hello team 
## I am new to keystone and i am getting this error

Mongo Error:

{ MongoError: failed to connect to server [localhost:27017] on first connect
    at .<anonymous> (C:\Users\Akshay Muralidhara\myproject\my-site\node_modules\
mongodb-core\lib\topologies\server.js:313:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (C:\Users\Akshay Muralidhara\myproject\my-site\node_modules\
mongodb-core\lib\connection\pool.js:271:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (C:\Users\Akshay Muralidhara\myproject\my-site\node_mo
dules\mongodb-core\lib\connection\connection.js:165:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1271:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect' }
Error: KeystoneJS (My Site) failed to start - Check that you are running `mongod
` in a separate process.
    at NativeConnection.<anonymous> (C:\Users\Akshay Muralidhara\myproject\my-si
te\node_modules\keystone\lib\core\openDatabaseConnection.js:58:10)
    at NativeConnection.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at NativeConnection.emit (events.js:188:7)
    at C:\Users\Akshay Muralidhara\myproject\my-site\node_modules\mongoose\lib\c
onnection.js:288:17
    at NativeConnection.Connection.error (C:\Users\Akshay Muralidhara\myproject\
my-site\node_modules\mongoose\lib\connection.js:489:12)
    at C:\Users\Akshay Muralidhara\myproject\my-site\node_modules\mongoose\lib\c
onnection.js:520:15
    at C:\Users\Akshay Muralidhara\myproject\my-site\node_modules\mongoose\lib\d
rivers\node-mongodb-native\connection.js:69:21
    at C:\Users\Akshay Muralidhara\myproject\my-site\node_modules\mongodb\lib\db
.js:229:14
    at .<anonymous> (C:\Users\Akshay Muralidhara\myproject\my-site\node_modules\
mongodb\lib\server.js:259:9)
    at g (events.js:286:16)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (C:\Users\Akshay Muralidhara\myproject\my-site\node_modules\
mongodb-core\lib\topologies\server.js:313:21)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)

when try to connect mongo with mongocompass i get this error Could not connect to MongoDB on the provided host and port

**Comment by AkshayMuralidhara** [comment]
Ok i got it

**Comment by jstockwin** [comment]
@AkshayMuralidhara Since you've worked this out, is it alright to close this issue? 
Also, what was the solution, just in case somebody else is having the same issue.

**Comment by Noviny** [comment]
Closing this issue for now.

@AkshayMuralidhara, would love to know how you solved it if you can share. 🙂

**Comment by mks148** [comment]
i have same problem @AkshayMuralidhara  can you please help me with this ?
Thanks

**Comment by cris1314** [comment]
same problem here :( anyone can share the solution? @AkshayMuralidhara

**Comment by cris1314** [comment]
I found the solution! @mks148  @Noviny  just need to execute mongo using "**mongod**" command on your **terminal** then in **other** **terminal** run **keystone** :) is just telling you that you **don't had initialize mondodb**. I hope this can be useful.
