### ISSUE TITLE
Keystone not starting

### ISSUE THREAD

**Issue by james-aiwip** [keystonejs/generator-keystone#228]
I've used this template, but keystone isn't serving anything. Any ideas ?

**Comment by thisboyiscrazy** [comment]
I have the same problem when I run

`node keystone.js`

I get

```
Error: /home/keystone/carterbearings.com/node_modules/bson/build/Release/bson.node: invalid ELF header
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/keystone/carterbearings.com/node_modules/bson/ext/index.js:15:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/keystone/carterbearings.com/node_modules/bson/lib/bson/index.js:3:24)
    at Module._compile (module.js:571:32)
js-bson: Failed to load c++ bson extension, using pure JS version

```

and it seems keystone is not fully starting.

**Comment by thisboyiscrazy** [comment]
This may be an upstream issue.

It seems the native js driver in mongoose@3.8.40 does not fire the 'open' event causing onMount to not get fired in keystone.

I changed node_packages/keystone/package.js to `"mongoose": "4.7.8"` then reinstall mongoose.

Also I had to `npm install unicode`

Then it worked

**Comment by Noviny** [comment]
We've upgraded the master branch to use keystone 4, which should resolve this issue.

Closing this issue for now, if the new version is still creating this issue, please comment/reopen.
