### ISSUE TITLE
yo keystone error:  args.includes is not a function

### ISSUE THREAD

**Issue by rdeils** [keystonejs/generator-keystone#248]
**Problem**
I'm trying to install keystone on Linux Mint (ubuntu 14 based) and when I run the command "yo keystone" I get the following error.

I appreciate any help! 

**Environment**
node version: v4.4.7
npm version: 2.15.8
mongodb version: v3.2.9-rc0
yeoman version: 1.8.5
os: Linux Mint xfce 17

**Error code**
```
 $ yo keystone
/usr/lib/node_modules/generator-keystone/app/index.js:14
	this.auto = args.includes('auto');
	                 ^

TypeError: args.includes is not a function
    at new KeystoneGenerator (/usr/lib/node_modules/generator-keystone/app/index.js:14:19)
    at Environment.instantiate (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:336:10)
    at Environment.create (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:313:15)
    at Environment.run (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:372:24)
    at /usr/lib/node_modules/yo/lib/cli.js:140:11
    at Array.forEach (native)
    at /usr/lib/node_modules/yo/lib/cli.js:139:9
    at Environment.resolver.lookup (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:50:12)
    at init (/usr/lib/node_modules/yo/lib/cli.js:115:7)
    at pre (/usr/lib/node_modules/yo/lib/cli.js:73:3)
```

**Comment by Noviny** [comment]
Hi @rdeils, #243 was the same issue, which we have solved on master. Unfortunately we haven't got a patch out to npm yet.

Going to leave this issue open until the patch is out.
