### ISSUE TITLE
Error: Cannot find module '@keystonejs/file-adapters'

### ISSUE THREAD

**Issue by williamhqs** [keystonejs/generator-keystone#289]
I'm following the https://www.keystonejs.com/keystonejs/file-adapters/ to create the file upload function, but I got the error:

```
ℹ Command: keystone dev
✔ Validated project entry file ./index.js
✔ Keystone server listening on port 3000
✖ Initialising Keystone instance
Error: Cannot find module '@keystonejs/file-adapters'
Require stack:
- /Users/william/B/testAdin/my-app/index.js
- /Users/william/B/testAdin/my-app/node_modules/@keystonejs/keystone/bin/utils.js
- /Users/william/B/testAdin/my-app/node_modules/@keystonejs/keystone/bin/commands/build.js
- /Users/william/B/testAdin/my-app/node_modules/@keystonejs/keystone/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/william/B/testAdin/my-app/index.js:8:30)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at executeDefaultServer (/Users/william/B/testAdin/my-app/node_modules/@keystonejs/keystone/bin/utils.js:96:64) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
```

Any help?

**Comment by gautamsi** [comment]
this repo is for [keystone v4](https://github.com/keystonejs/keystone-classic), file your issue here for this => https://github.com/keystonejs/keystone/issues

**Comment by williamhqs** [comment]
OK thanks, then let me close this one.
