### ISSUE TITLE
Generator fails on Windows 8 cygwin

### ISSUE THREAD

**Issue by dilignt** [keystonejs/generator-keystone#63]
I get the following error when trying to run the generator

```
Mike@Mike-VAIO /cygdrive/c/workspaces/web
$ yo keystone

Welcome to KeystoneJS.


net.js:156
    this._handle.open(options.fd);
                 ^
Error: EINVAL, invalid argument
    at new Socket (net.js:156:18)
    at process.stdin (node.js:664:19)
    at Object.Interface.createInterface (C:\Users\Mike\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\node_modules\inquirer\node_modules\readline2\index.js:31:43)
    at PromptUI.UI (C:\Users\Mike\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\node_modules\inquirer\lib\ui\baseUI.js:23:40)
    at new PromptUI (C:\Users\Mike\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\node_modules\inquirer\lib\ui\prompt.js:26:8)
    at Object.inquirer.prompt (C:\Users\Mike\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\node_modules\inquirer\lib\inquirer.js:39:10)
    at TerminalAdapter._prompt [as prompt] (C:\Users\Mike\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\lib\env\adapter.js:36:19)
    at KeystoneGenerator.Base.prompt (C:\Users\Mike\AppData\Roaming\npm\node_modules\generator-keystone\node_modules\yeoman-generator\lib\base.js:186:20)
    at KeystoneGenerator.prompts (C:\Users\Mike\AppData\Roaming\npm\node_modules\generator-keystone\app\index.js:130:7)
    at C:\Users\Mike\AppData\Roaming\npm\node_modules\generator-keystone\node_modules\yeoman-generator\lib\base.js:387:14
```

**Comment by Noviny** [comment]
Old unproduced bug. Closing as we clear up the issue track.
